global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']



  #  monitoramento para seus servi√ßos depois
  #- job_name: 'postgres-eco'
  #  static_configs:
  #    - targets: ['postgres-eco:5432']
  #  metrics_path: /metrics
  #  scheme: http

  # - job_name: 'sonarqube'
  #  static_configs:
  #    - targets: ['sonarqube:9000']
  #  metrics_path: /metrics
  #  scheme: http